### ISSUE TITLE
Better rendering of latex equations

### ISSUE THREAD

**Issue by DidierRLopes** [souzatharsis/tamingLLMs#17]
<img width="1362" alt="Screenshot 2024-12-29 at 4 06 48 PM" src="https://github.com/user-attachments/assets/4b861ef8-a39d-4f7e-8384-f2ff314f7a3d" />

Here: https://www.souzatharsis.com/tamingLLMs/notebooks/alignment.html#from-raw-capabilities-to-preference-alignment

https://sphinx-rtd-trial.readthedocs.io/en/latest/ext/math.html

**Comment by souzatharsis** [comment]
Thanks.

I've followed the recommended config. However, for some reason, it only renders correctly after refresh.

No worries, it will be in proper latex in the pdf and hard copy versions.

**Comment by souzatharsis** [comment]
OK. Math formula has been simplified and should load faster and correctly at first try.
Thanks for reporting.

Further, now the book is available at www.tamingllms.com
